[package]
name = "writer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = "0.2.0"
convert_case = "0.6.0"
error-stack = "0.3.1"
model = { version = "0.1.0", path = "../model" }

[dev-dependencies]
indoc = "2.0.1"
serde_yaml = "0.9.21"
tempfile = "3.5.0"
